// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifvktibgarrprfbwuupe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmdmt0aWJnYXJycHJmYnd1dXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MDY5NjIsImV4cCI6MjA5NTM4Mjk2Mn0.bSS8deKzZNXVuOVUgndX-M8BMsT-kL4lg-cieTANFaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});